# Nome do Projeto
spring.application.name=projectinvite

# Configuração do Banco de Dados em Nuvem (Neon.tech)
spring.datasource.url=jdbc:postgresql://ep-bold-sound-aqghl1xq.c-8.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_xopY9kKuZI4O&sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver

# Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Porta do Servidor Local
server.port=8080