spring.application.name=projectinvite

# Configurações de Banco de Dados
spring.datasource.url=jdbc:postgresql://ep-bold-sound-aqghl1xq.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_O7DWmrwBQk8G
spring.datasource.driverClassName=org.postgresql.Driver

# Forçar o Hibernate a reconhecer o PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Porta
server.port=8080