spring.application.name=projectinvite

# O Spring vai tentar ler do ambiente; se não achar, usará o valor fixo logo após os dois pontos
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-bold-sound-aqghl1xq.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:npg_O7DWmrwBQk8G}
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080